### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by varga** [JakeSharp/ProductSliderM2#1]
I do not know why, but it does not work in http://dfdufry.grouptools.com.br/

What happens?

**Comment by chombe** [comment]
Hi varga,

Can you please first check if extension is properly installed and enabled.
If so, it should be listed in Magento admin Store -> Configuration -> JakeSharp -> Product Slider

On General tab you can enable extension.

**Comment by chombe** [comment]
Closing this one
