### ISSUE TITLE
Unknown module

### ISSUE THREAD

**Issue by faiyaz1234** [JakeSharp/ProductSliderM2#10]
after uploading file to the instructed directory i got this error in command line 
Unknown module(s): 'JakeSharp_Core'
 when i run the command in root directory of my application- sudo bin/magento module:enable JakeSharp_Core.
Help me please.
Thanks

**Comment by chombe** [comment]
hy @faiyaz1234 
this module is not maintained anymore. 
Please use [this](https://github.com/trive-digital/Revo-ProductSliderM2) instead.
Or better, install it with composer https://packagist.org/packages/trive/module-revo

Thanks

**Comment by faiyaz1234** [comment]
Thanks @chombe for your fast reply. I m looking forward on your link you provided.
