### ISSUE TITLE
Error during compilation after enable the module

### ISSUE THREAD

**Issue by milkolori** [JakeSharp/ProductSliderM2#2]
There is error during magento 2 compilation after enabling the module. The steps which I followed are:
1. bin/magento module:enable JakeSharp_Core
2. bin/magento module:enable JakeSharp_Productslider
3. bin/magento setup:upgrade
4. delete  var/di folder
5.  magento setup:di:compile

During compilation I receive the following error:

`JakeSharp\Productslider\Block\Adminhtml\Slider\Edit\Tab\Advanced
        Incorrect dependency in class JakeSharp\Productslider\Block\Adminhtml\Slider\Edit\Tab\Advanced in /Applications/MAMP/htdocs/magento2/vendor/jakesharp/module-productslider/Block/Adminhtml/Slider/Edit/Tab/Advanced.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
    JakeSharp\Productslider\Block\Adminhtml\Slider\Edit\Tab\General
        Incorrect dependency in class JakeSharp\Productslider\Block\Adminhtml\Slider\Edit\Tab\General in /Applications/MAMP/htdocs/magento2/vendor/jakesharp/module-productslider/Block/Adminhtml/Slider/Edit/Tab/General.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
    JakeSharp\Productslider\Block\Slider
        Incorrect dependency in class JakeSharp\Productslider\Block\Slider in /Applications/MAMP/htdocs/magento2/vendor/jakesharp/module-productslider/Block/Slider.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Framework\View\LayoutInterface already exists in context object
Total Errors Count: 3`

Any help on that?

**Comment by chombe** [comment]
Hi @milkolori 

Error should be fixed now.
Thank you for reporting this.

**Comment by milkolori** [comment]
Thank you for the fast response. Can you please publish the package so I can update it with composer?

**Comment by chombe** [comment]
@milkolori no problem, it's published...

**Comment by milkolori** [comment]
Thank you very much. It is fixed now.
