### ISSUE TITLE
Slider identifier

### ISSUE THREAD

**Issue by 7krasov** [JakeSharp/ProductSliderM2#8]
Hello, guys :-) It will be great if we can have 'slider_code' field for not to link to site instance (e.g. local id can be 1, server id can be 2 but the meaning of slider should be the same, slider_code ="homepage_top_slider"), especially in xml or php

**Comment by zeljkoprsa** [comment]
Hi, @7krasov I'm not sure what you are suggesting here. Could you elaborate it further?

Also, please note that we replaced this version which is no longer maintained with this one:
https://github.com/trive-digital/Revo-ProductSliderM2

If you could please elaborate your request there. Thanks.
